## **Import Important Libraries**

In [1]:
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt

## **Dataset Load**

In [2]:
df = pd.read_csv("mental_health.csv")

In [4]:
# See The first 5 rows 
df.head().T

,0,1,2,3,4
Age,40,33,42,53,32
Gender,Male,Male,Male,Male,Female
Country,USA,India,Other,Germany,India
Education,Some College,Bachelor,High School,Bachelor,Bachelor
Marital_Status,Single,Married,Single,Single,Single
Income_Level,Middle,Middle,Low,Middle,High
Employment_Status,Full-time,Unemployed,Full-time,Unemployed,Student
Work_Hours_Per_Week,27,47,53,42,13
Remote_Work,No,No,No,No,No
Job_Satisfaction,6,6,1,10,4
Work_Stress_Level,7,1,3,3,7
Work_Life_Balance,7,5,8,5,7
Ever_Bullied_At_Work,0,0,0,0,1
Company_Mental_Health_Support,No,Not sure,Not sure,No,Not sure
Exercise_Per_Week,1-2 times,1-2 times,3-4 times,Never,1-2 times
Sleep_Hours_Night,6.2,9.6,7.7,6.4,7.7
Caffeine_Drinks_Day,3,3,1,1,0
Alcohol_Frequency,Never,Weekly,Never,Rarely,Rarely
Smoking,Former,Current,Former,Former,Current
Screen_Time_Hours_Day,8.3,8.6,11.4,6.4,7.6
Social_Media_Hours_Day,4.8,0.0,3.0,2.9,4.0
Hobby_Time_Hours_Week,7,7,0,5,2
Diet_Quality,Average,Average,Good,Average,Excellent
Financial_Stress,9,9,2,1,8
Feeling_Sad_Down,8,1,4,3,6
Loss_Of_Interest,3,10,7,8,8
Sleep_Trouble,10,4,8,10,4
Fatigue,5,9,8,10,5
Poor_Appetite_Or_Overeating,9,4,4,2,4
Feeling_Worthless,4,10,9,2,5
Concentration_Difficulty,4,6,10,5,7
Anxious_Nervous,1,8,1,3,10
Panic_Attacks,0,2,0,1,1
Mood_Swings,9,5,9,0,0
Irritability,2,9,9,2,10
Obsessive_Thoughts,3,9,7,3,10
Compulsive_Behavior,0,3,6,3,1
Self_Harm_Thoughts,0,0,0,0,0
Suicidal_Thoughts,0,0,0,0,0
Family_History_Mental_Illness,1,0,0,1,0
Previously_Diagnosed,1,0,0,0,1
Ever_Sought_Treatment,1,0,1,0,0
On_Therapy_Now,0,0,0,1,0
On_Medication,0,0,0,0,0
Trauma_History,0,0,1,0,0
Social_Support,9,3,5,1,1
Close_Friends_Count,3,2,3,3,5
Feel_Understood,4,7,6,10,1
Loneliness,6,7,9,5,6
Discuss_Mental_Health,Sometimes,Sometimes,Sometimes,Never,Sometimes
Has_Mental_Health_Issue,1,1,1,1,1

In [5]:
# See the last 5 rows in this dataset
df.tail().T

,9995,9996,9997,9998,9999
Age,50,18,26,40,42
Gender,Female,Female,Male,Female,Female
Country,India,UK,Brazil,Brazil,Other
Education,High School,Some College,Master,Some College,PhD
Marital_Status,Divorced,Divorced,Married,Single,Married
Income_Level,High,Middle,High,Low,High
Employment_Status,Student,Full-time,Full-time,Full-time,Full-time
Work_Hours_Per_Week,42,33,34,42,44
Remote_Work,No,Yes,No,No,Yes
Job_Satisfaction,4,6,4,3,4
Work_Stress_Level,7,5,4,7,6
Work_Life_Balance,1,9,3,7,2
Ever_Bullied_At_Work,0,0,0,0,1
Company_Mental_Health_Support,Yes,No,No,Yes,No
Exercise_Per_Week,Never,1-2 times,3-4 times,Never,5+ times
Sleep_Hours_Night,5.8,8.9,7.5,6.5,4.7
Caffeine_Drinks_Day,2,5,0,0,2
Alcohol_Frequency,Never,Daily,Weekly,Weekly,Rarely
Smoking,Former,Never,Never,Former,Former
Screen_Time_Hours_Day,7.6,9.1,6.6,7.0,5.3
Social_Media_Hours_Day,0.0,5.1,6.1,4.9,1.3
Hobby_Time_Hours_Week,2,8,8,17,9
Diet_Quality,Good,Average,Average,Average,Good
Financial_Stress,8,8,5,3,9
Feeling_Sad_Down,8,10,1,2,9
Loss_Of_Interest,9,0,9,8,6
Sleep_Trouble,4,10,8,4,5
Fatigue,0,1,8,0,10
Poor_Appetite_Or_Overeating,8,10,10,0,2
Feeling_Worthless,0,10,3,1,6
Concentration_Difficulty,2,9,4,6,7
Anxious_Nervous,6,5,0,9,8
Panic_Attacks,1,0,0,0,1
Mood_Swings,2,3,10,8,9
Irritability,1,2,1,5,7
Obsessive_Thoughts,4,9,4,9,9
Compulsive_Behavior,8,1,0,9,9
Self_Harm_Thoughts,0,0,0,0,1
Suicidal_Thoughts,0,1,0,0,0
Family_History_Mental_Illness,0,1,0,0,0
Previously_Diagnosed,0,0,0,0,0
Ever_Sought_Treatment,0,1,0,1,0
On_Therapy_Now,0,0,0,0,1
On_Medication,0,0,0,0,0
Trauma_History,0,0,0,0,0
Social_Support,5,1,4,5,4
Close_Friends_Count,5,3,6,3,1
Feel_Understood,6,10,5,4,2
Loneliness,4,2,5,1,7
Discuss_Mental_Health,Sometimes,Rarely,Rarely,Sometimes,Sometimes
Has_Mental_Health_Issue,1,1,0,1,1

In [6]:
# Dataset columns
df.columns

Index(['Age', 'Gender', 'Country', 'Education', 'Marital_Status',
       'Income_Level', 'Employment_Status', 'Work_Hours_Per_Week',
       'Remote_Work', 'Job_Satisfaction', 'Work_Stress_Level',
       'Work_Life_Balance', 'Ever_Bullied_At_Work',
       'Company_Mental_Health_Support', 'Exercise_Per_Week',
       'Sleep_Hours_Night', 'Caffeine_Drinks_Day', 'Alcohol_Frequency',
       'Smoking', 'Screen_Time_Hours_Day', 'Social_Media_Hours_Day',
       'Hobby_Time_Hours_Week', 'Diet_Quality', 'Financial_Stress',
       'Feeling_Sad_Down', 'Loss_Of_Interest', 'Sleep_Trouble', 'Fatigue',
       'Poor_Appetite_Or_Overeating', 'Feeling_Worthless',
       'Concentration_Difficulty', 'Anxious_Nervous', 'Panic_Attacks',
       'Mood_Swings', 'Irritability', 'Obsessive_Thoughts',
       'Compulsive_Behavior', 'Self_Harm_Thoughts', 'Suicidal_Thoughts',
       'Family_History_Mental_Illness', 'Previously_Diagnosed',
       'Ever_Sought_Treatment', 'On_Therapy_Now', 'On_Medication',
       'Trauma_History', 'Social_Support', 'Close_Friends_Count',
       'Feel_Understood', 'Loneliness', 'Discuss_Mental_Health',
       'Has_Mental_Health_Issue'],
      dtype='object')

In [7]:
# Dataset Dtype check
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 51 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Age                            10000 non-null  int64
 1   Gender                         10000 non-null  object
 2   Country                        10000 non-null  object
 3   Education                      10000 non-null  object
 4   Marital_Status                 10000 non-null  object
 5   Income_Level                   10000 non-null  object
 6   Employment_Status              10000 non-null  object
 7   Work_Hours_Per_Week            10000 non-null  int64
 8   Remote_Work                    10000 non-null  object
 9   Job_Satisfaction               10000 non-null  int64
 10  Work_Stress_Level              10000 non-null  int64
 11  Work_Life_Balance              10000 non-null  int64
 12  Ever_Bullied_At_Work           10000 non-null  int64
 13  Company_Mental_Health_Support  10000 non-null  object
 14  Exercise_Per_Week              10000 non-null  object
 15  Sleep_Hours_Night              10000 non-null  float64
 16  Caffeine_Drinks_Day            10000 non-null  int64
 17  Alcohol_Frequency              10000 non-null  object
 18  Smoking                        10000 non-null  object
 19  Screen_Time_Hours_Day          10000 non-null  float64
 20  Social_Media_Hours_Day         10000 non-null  float64
 21  Hobby_Time_Hours_Week          10000 non-null  int64
 22  Diet_Quality                   10000 non-null  object
 23  Financial_Stress               10000 non-null  int64
 24  Feeling_Sad_Down               10000 non-null  int64
 25  Loss_Of_Interest               10000 non-null  int64
 26  Sleep_Trouble                  10000 non-null  int64
 27  Fatigue                        10000 non-null  int64
 28  Poor_Appetite_Or_Overeating    10000 non-null  int64
 29  Feeling_Worthless              10000 non-null  int64
 30  Concentration_Difficulty       10000 non-null  int64
 31  Anxious_Nervous                10000 non-null  int64
 32  Panic_Attacks                  10000 non-null  int64
 33  Mood_Swings                    10000 non-null  int64
 34  Irritability                   10000 non-null  int64
 35  Obsessive_Thoughts             10000 non-null  int64
 36  Compulsive_Behavior            10000 non-null  int64
 37  Self_Harm_Thoughts             10000 non-null  int64
 38  Suicidal_Thoughts              10000 non-null  int64
 39  Family_History_Mental_Illness  10000 non-null  int64
 40  Previously_Diagnosed           10000 non-null  int64
 41  Ever_Sought_Treatment          10000 non-null  int64
 42  On_Therapy_Now                 10000 non-null  int64
 43  On_Medication                  10000 non-null  int64
 44  Trauma_History                 10000 non-null  int64
 45  Social_Support                 10000 non-null  int64
 46  Close_Friends_Count            10000 non-null  int64
 47  Feel_Understood                10000 non-null  int64
 48  Loneliness                     10000 non-null  int64
 49  Discuss_Mental_Health          10000 non-null  object
 50  Has_Mental_Health_Issue        10000 non-null  int64
dtypes: float64(3), int64(35), object(13)
memory usage: 3.9+ MB

In [8]:
# Statistical Analysis
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Age,10000.0,34.94790,11.156390,18.0,26.0,34.0,43.0,75.0
Work_Hours_Per_Week,10000.0,39.65790,10.016711,0.0,33.0,40.0,46.0,74.0
Job_Satisfaction,10000.0,5.50270,2.884341,1.0,3.0,6.0,8.0,10.0
Work_Stress_Level,10000.0,5.49390,2.881630,1.0,3.0,6.0,8.0,10.0
Work_Life_Balance,10000.0,5.48940,2.875572,1.0,3.0,5.0,8.0,10.0
Ever_Bullied_At_Work,10000.0,0.24740,0.431523,0.0,0.0,0.0,0.0,1.0
Sleep_Hours_Night,10000.0,6.81545,1.377975,3.0,5.9,6.8,7.7,11.0
Caffeine_Drinks_Day,10000.0,2.02330,1.427432,0.0,1.0,2.0,3.0,8.0
Screen_Time_Hours_Day,10000.0,7.06459,2.955874,1.0,5.0,7.0,9.1,16.0
Social_Media_Hours_Day,10000.0,3.14181,2.254204,0.0,1.3,3.0,4.7,12.0
Hobby_Time_Hours_Week,10000.0,4.78030,3.563552,0.0,2.0,5.0,7.0,19.0
Financial_Stress,10000.0,5.48260,2.886231,1.0,3.0,5.0,8.0,10.0
Feeling_Sad_Down,10000.0,4.98960,3.156468,0.0,2.0,5.0,8.0,10.0
Loss_Of_Interest,10000.0,5.01820,3.148342,0.0,2.0,5.0,8.0,10.0
Sleep_Trouble,10000.0,5.00080,3.164459,0.0,2.0,5.0,8.0,10.0
Fatigue,10000.0,5.00330,3.133189,0.0,2.0,5.0,8.0,10.0
Poor_Appetite_Or_Overeating,10000.0,4.96840,3.150967,0.0,2.0,5.0,8.0,10.0
Feeling_Worthless,10000.0,4.98420,3.171207,0.0,2.0,5.0,8.0,10.0
Concentration_Difficulty,10000.0,4.95100,3.155376,0.0,2.0,5.0,8.0,10.0
Anxious_Nervous,10000.0,4.98740,3.156111,0.0,2.0,5.0,8.0,10.0
Panic_Attacks,10000.0,0.54690,0.980967,0.0,0.0,0.0,1.0,4.0
Mood_Swings,10000.0,5.04210,3.165964,0.0,2.0,5.0,8.0,10.0
Irritability,10000.0,5.03220,3.147055,0.0,2.0,5.0,8.0,10.0
Obsessive_Thoughts,10000.0,4.94220,3.180043,0.0,2.0,5.0,8.0,10.0
Compulsive_Behavior,10000.0,4.95990,3.154598,0.0,2.0,5.0,8.0,10.0
Self_Harm_Thoughts,10000.0,0.07810,0.268342,0.0,0.0,0.0,0.0,1.0
Suicidal_Thoughts,10000.0,0.09520,0.293506,0.0,0.0,0.0,0.0,1.0
Family_History_Mental_Illness,10000.0,0.30440,0.460176,0.0,0.0,0.0,1.0,1.0
Previously_Diagnosed,10000.0,0.24800,0.431873,0.0,0.0,0.0,0.0,1.0
Ever_Sought_Treatment,10000.0,0.36220,0.480660,0.0,0.0,0.0,1.0,1.0
On_Therapy_Now,10000.0,0.19100,0.393109,0.0,0.0,0.0,0.0,1.0
On_Medication,10000.0,0.18430,0.387748,0.0,0.0,0.0,0.0,1.0
Trauma_History,10000.0,0.25060,0.433380,0.0,0.0,0.0,1.0,1.0
Social_Support,10000.0,5.45970,2.882986,1.0,3.0,5.0,8.0,10.0
Close_Friends_Count,10000.0,4.01930,1.998431,0.0,3.0,4.0,5.0,13.0
Feel_Understood,10000.0,5.46970,2.872021,1.0,3.0,5.0,8.0,10.0
Loneliness,10000.0,5.44970,2.862322,1.0,3.0,5.0,8.0,10.0
Has_Mental_Health_Issue,10000.0,0.92160,0.268813,0.0,1.0,1.0,1.0,1.0

In [9]:
df.dtypes

Age                                int64
Gender                            object
Country                           object
Education                         object
Marital_Status                    object
Income_Level                      object
Employment_Status                 object
Work_Hours_Per_Week                int64
Remote_Work                       object
Job_Satisfaction                   int64
Work_Stress_Level                  int64
Work_Life_Balance                  int64
Ever_Bullied_At_Work               int64
Company_Mental_Health_Support     object
Exercise_Per_Week                 object
Sleep_Hours_Night                float64
Caffeine_Drinks_Day                int64
Alcohol_Frequency                 object
Smoking                           object
Screen_Time_Hours_Day            float64
Social_Media_Hours_Day           float64
Hobby_Time_Hours_Week              int64
Diet_Quality                      object
Financial_Stress                   int64
Feeling_Sad_Down                   int64
Loss_Of_Interest                   int64
Sleep_Trouble                      int64
Fatigue                            int64
Poor_Appetite_Or_Overeating        int64
Feeling_Worthless                  int64
Concentration_Difficulty           int64
Anxious_Nervous                    int64
Panic_Attacks                      int64
Mood_Swings                        int64
Irritability                       int64
Obsessive_Thoughts                 int64
Compulsive_Behavior                int64
Self_Harm_Thoughts                 int64
Suicidal_Thoughts                  int64
Family_History_Mental_Illness      int64
Previously_Diagnosed               int64
Ever_Sought_Treatment              int64
On_Therapy_Now                     int64
On_Medication                      int64
Trauma_History                     int64
Social_Support                     int64
Close_Friends_Count                int64
Feel_Understood                    int64
Loneliness                         int64
Discuss_Mental_Health             object
Has_Mental_Health_Issue            int64
dtype: object

## **EDA**

In [10]:
# Check the missing values in this dataset
df.isna().sum()

Age                              0
Gender                           0
Country                          0
Education                        0
Marital_Status                   0
Income_Level                     0
Employment_Status                0
Work_Hours_Per_Week              0
Remote_Work                      0
Job_Satisfaction                 0
Work_Stress_Level                0
Work_Life_Balance                0
Ever_Bullied_At_Work             0
Company_Mental_Health_Support    0
Exercise_Per_Week                0
Sleep_Hours_Night                0
Caffeine_Drinks_Day              0
Alcohol_Frequency                0
Smoking                          0
Screen_Time_Hours_Day            0
Social_Media_Hours_Day           0
Hobby_Time_Hours_Week            0
Diet_Quality                     0
Financial_Stress                 0
Feeling_Sad_Down                 0
Loss_Of_Interest                 0
Sleep_Trouble                    0
Fatigue                          0
Poor_Appetite_Or_Overeating      0
Feeling_Worthless                0
Concentration_Difficulty         0
Anxious_Nervous                  0
Panic_Attacks                    0
Mood_Swings                      0
Irritability                     0
Obsessive_Thoughts               0
Compulsive_Behavior              0
Self_Harm_Thoughts               0
Suicidal_Thoughts                0
Family_History_Mental_Illness    0
Previously_Diagnosed             0
Ever_Sought_Treatment            0
On_Therapy_Now                   0
On_Medication                    0
Trauma_History                   0
Social_Support                   0
Close_Friends_Count              0
Feel_Understood                  0
Loneliness                       0
Discuss_Mental_Health            0
Has_Mental_Health_Issue          0
dtype: int64